---
- hosts: ubuntu
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes


- hosts: centos
  remote_user: root
  tasks:
  - name: update repository index
    yum:
      update_cache: yes